version: '3.8'

services:
  
  cache-requester:
    image: appropriate/curl
    container_name: cache-requester
    # depends_on:
      # - iot-device
    command: /bin/sh -c "while true; do curl -s -X POST https://nonelectrically-jocund-scot.ngrok-free.dev/api/v1/cache/process; sleep 120; done"
    restart: unless-stopped